### ISSUE TITLE
New pickaxes

### ISSUE THREAD

**Issue by Monniasza** [MultiMachineBuilder/MultiMachineBuilder#127]
Add the following picaxes to widen the choice of mining equipment:
- stone - 150 durability, 1s to mine a block
- iron - 250 durability, 640ms to mine a block
- steel - 350 durability, 400 ms to mine a block
- stainless - 600 durability, 280 ms to mine a block

and change rudimentary to 200 durability

**Comment by tempest138** [comment]
Hello, I'm interested intackling this problem. Could you elaborate on it a little on the issue and how I can start contributing, it'd be really helpful.

**Comment by Monniasza** [comment]
@tempest138 Follow the [contributing guidelines](https://github.com/MultiMachineBuilder/MultiMachineBuilder/blob/master/CONTRIBUTING.md) for guidance.
You can also learn at https://github.com/firstcontributions/first-contributions.

In `ContentsItems`:
* Create pickaxes like this:
  ```java
  /** The most basic pickaxe available in the game */
  @NN public static final PickaxeType pickWood = Pickaxe.create(100, 100, "item/wood pick.png", 
  "#pick-wood", "pick.wood");
  ```
  , and fill out fields:
    1. time: time to mine a block in ticks (each lasts 20 ms)
    2. durability: maximum uses of the pickaxe
    3. texture: path texture of the pickaxe
    4. title: title of the pickaxe
    5. id: ID of the pickaxe
* Change the rudimentary pickaxe's durability rating to 200

In `src/mmb/bundle.properties`:
* Place your pickaxe translation keys after these lines:
  ```
  pick-wood=Wooden pickaxe
  pick-rud=Rudimentary pickaxe
  ```

In textures:
* Recolor existing pickaxes according to the material's color.
  The brighter color should be taken from and edge of the ingot.
  The darker color should be taken from the front face of the ingot.
  You can use a screenshot to do that.
  The stainless pickaxe texture is already present and use it in the pickaxe.
  Place the textures in 'textures/item'
* Delete pickaxe head textures

In `ContentsRecipes`:
* For metals, add recipes like this, in the `_tools()` method:
  ```java
  crafting.addRecipe(new FixedGrid<>(3,
  Materials.rudimentary.nugget, Materials.rudimentary.base,   Materials.rudimentary.nugget,
  null,                         Materials.rudimentary.nugget, null,
  null,                         Materials.rudimentary.nugget, null), ItemRaw.make(pickRudimentary), 1);
  ```
  , in the following pattern:
  ```
  fif
   f
   f
  ```
  , where `f` is a fragment and `i` is and ingot for appropriate material
* For stone, add recipe in the following pattern:
  ```
  sss
   s
   s
  ```
* Use raw items in the output, like `ItemRaw.make(pickRudimentary)`, instead of item entities
* Place all pickaxe recipes below the following line:
  ```java
  null,                         Materials.rudimentary.nugget, null), ItemRaw.make(pickRudimentary), 1);
  ```

**Comment by Monniasza** [comment]
@tempest138 If you don't respond by May 31, I'll take over this task.

**Comment by Monniasza** [comment]
@tempest138 Are you still working on it? If not, I can propose easier tasks and take over it.

**Comment by Monniasza** [comment]
@tempest138  If you don't respond by July 5, I'll take over this task

**Comment by PKCPablo** [comment]
@Monniasza is this feature still open to develop?

**Comment by Monniasza** [comment]
@PKCPablo Yes

**Comment by PKCPablo** [comment]
@Monniasza could I try to develop it?

**Comment by Monniasza** [comment]
@PKCPablo Yes

**Comment by PKCPablo** [comment]
@Monniasza, nice, so I will set up the IDE and start working on it. Could you assign me to it, and should I do anything more? It is my first time contributing to an open-source project.

**Comment by Monniasza** [comment]
@PKCPablo Feel free to ask me if you have any issues,

**Comment by PKCPablo** [comment]
@Monniasza Yes, thanks! I'm implementing the feature requested, but I'm having a little trouble with SonarLint:

![image](https://github.com/MultiMachineBuilder/MultiMachineBuilder/assets/79366518/a984b08d-dc5b-43ae-b7b0-77c31efc23e8)

**Comment by Monniasza** [comment]
@PKCPablo Have you reliable Internet access on your development machine?

**Comment by PKCPablo** [comment]
@Monniasza some times it has micro-cuts like the internet goes out some milliseconds. Maybe it is that?

**Comment by PKCPablo** [comment]
@Monniasza i also saw there is a copper pickaxe texture, should I implement it too??

**Comment by Monniasza** [comment]
@PKCPablo Use mmb.engine.java2d.ColorMul to generate textures. Implement all given tasks. Maybe your internet is unreliable.

**Comment by PKCPablo** [comment]
@Monniasza I think I've done what you requested. I'll do a PR so you can check it :)

**Comment by Monniasza** [comment]
@PKCPablo How do I test a PR in Eclipse?

**Comment by Monniasza** [comment]
@PKCPablo Would you want to do https://github.com/MultiMachineBuilder/MultiMachineBuilder/issues/129 too?

**Comment by PKCPablo** [comment]
@Monniasza I'll check it later, but most likely yes
