### ISSUE TITLE
Deprecate item bucket and integrate its functionality into Standard Tool

### ISSUE THREAD

**Issue by Monniasza** [MultiMachineBuilder/MultiMachineBuilder#128]
The item pickup should be handled by a standard tool, to allow for items to be dropped in survival.
Use Alt+LMB to drop a single item, 
Alt+Ctrl+LMB to drop a single item stack, 
Alt+RMB to pick up a single item
and Alt+Ctrl+RMB to pick up all items

**Comment by Kaushik2201** [comment]
I want to contribute in this but have never tried it before but ready to work for it can u assign it to me and guide me how to work on it . Thankyou

**Comment by Monniasza** [comment]
@Kaushik2201 To contribute, follow the contributing guidelines. They contain useful information.

Import your fork in Eclipse and study the defined items. Use nullability annotations for all of your code.

**Comment by Kaushik2201** [comment]
okay Ill go through it and start working on it

**Comment by Monniasza** [comment]
@Kaushik2201 Respond again if you encounter any problems

**Comment by Kaushik2201** [comment]
I have done the setup and have gone through the code could you please elaborate the issue that will be a great help so that i can continue further

**Comment by Monniasza** [comment]
@Kaushik2201 

The item pickup should be handled by a standard tool, to allow for items to be dropped in survival.

Make following keybinds do given actions in the standard tool:
- Alt+LMB to drop a single item,
- Alt+Ctrl+LMB to drop a single item stack,
- Alt+RMB to pick up a single item
- Alt+Ctrl+RMB to pick up all items

Strike the texture of the item bucket out, like done for pickaxe workbench, and add recipe which recovers its ingredients.
Additionally, change the title of the item to indicate that item is deprecated and to be removed in 0.7, like shown at the bottom of the current item list. I'll do the Polish translation. Move the translation key to the bottom of the translation file in both Polish and English.
Remove the item bucket window tool code completely, and make an item bucket a regular item.
Tag the item with `@Deprecated` and `@DeprecatedExtra` annotations and add `deprecated` item tag to it.

**Comment by Kaushik2201** [comment]
okay so I will try my best and I have started working on this project.

**Comment by Monniasza** [comment]
@Kaushik2201 File a PR when done.

**Comment by Kaushik2201** [comment]
I have added toolstd 5 ,6,7,8 in tool in Bundle.properties am I on correct track ?

**Comment by Monniasza** [comment]
@Kaushik2201 They're in correct series. I'll do Polish translations of them.

**Comment by Monniasza** [comment]
@Kaushik2201 Make commits often to combat data loss.

**Comment by Kaushik2201** [comment]
I have made a pr toolstd updated #146 update me if its wrong

**Comment by Monniasza** [comment]
@Kaushik2201 You have only changed tooltips, but not moved the item bucket's functionality into standard tool or deprecated the item.

**Comment by Kaushik2201** [comment]
Okay noted I will do that

**Comment by Kaushik2201** [comment]
I cannot figure out to move item in bucket's functionality into standard tool

**Comment by Monniasza** [comment]
@Kaushik2201 Add keybinds to the standard tool.

**Comment by Kaushik2201** [comment]
The changes will be in ToolStandard.java file under keyboard section. I am correct on this ?

**Comment by Monniasza** [comment]
@Kaushik2201 Take the Ctrl, Alt and Shift keys from the world window.

**Comment by Monniasza** [comment]
See also #147

**Comment by Kaushik2201** [comment]
Okay I ll look into it

**Comment by Kaushik2201** [comment]
Thank You this comments encourages me

**Comment by Monniasza** [comment]
@Kaushik2201 Have you come up with reusable functions?

**Comment by Kaushik2201** [comment]
No not yet

**Comment by Kaushik2201** [comment]
Okay but actually our clg exams are going on thats y I couldn't do it

**Comment by Monniasza** [comment]
@Kaushik2201 Respond again after exams

**Comment by Monniasza** [comment]
@Kaushik2201 Could you continue working on it?

**Comment by Monniasza** [comment]
@Kaushik2201 When it is going to be ready?

**Comment by Monniasza** [comment]
@Kaushik2201 Are you still working on it? If not, I can propose easier tasks and take over it.

**Comment by Kaushik2201** [comment]
Actually something has gone wrong here with my system thats why u can take over I am sorry

**Comment by Monniasza** [comment]
@Kaushik2201 I'll take over it

**Comment by Kaushik2201** [comment]
Yeah Thanks
