### ISSUE TITLE
Remove the special offer prank

### ISSUE THREAD

**Issue by Monniasza** [MultiMachineBuilder/MultiMachineBuilder#131]
The special offer in the game was a prank.
Remove it by removing the garbler code, conditional garbling logic, translation keys about the special offer and the yellow special offer button completely. Retain anything HalfVec and OpenGL related.

**Comment by Monniasza** [comment]
@piyush280599 Could you want to work on this, please?

**Comment by piyush280599** [comment]
@Monniasza Sure I will.

**Comment by piyush280599** [comment]
@Monniasza Can you please elaborate a little? It would be a great help. Thanks!

**Comment by Monniasza** [comment]
@piyush280599 Remove the following:
* the yellow special offer button in the main menu
    * `MainMenu.prank`
* Conditional garbling logic:
    * `GlobalSettings.UTF8Control`
    * `GlobalSettings.garbler`
    * conditional garbling logic in `GlobalSettings.injectResources(ResourceBundle)`
    * the garbler setting
* prank translation keys (in all languages, at src/mmb/bundle*.properties)
    * `AprilFoolsGarblerPrank`
    * `AprilFoolsGarblerPrank2'
    * `AprilFoolsGarblerTooltip`

**Comment by Monniasza** [comment]
@piyush280599 If you don't respond by May 31, I'll take over this task.

**Comment by Monniasza** [comment]
@piyush280599 No response, taken over
