### ISSUE TITLE
Changing movement keys

### ISSUE THREAD

**Issue by PKCPablo** [MultiMachineBuilder/MultiMachineBuilder#196]
Most of the games use both arrows and WASD keys to move, maybe it would be fine to put the moving camera feature on the mouse buttons allowing WASD keys for movement?

**Comment by Monniasza** [comment]
Camera motion is primary method of motion in MultiMachineBuilder.

**Comment by PKCPablo** [comment]
But wouldn't it be easier and faster to move with the mouse?
