### ISSUE TITLE
[Typo] Misspelled button to remove all items

### ISSUE THREAD

**Issue by Monniasza** [MultiMachineBuilder/MultiMachineBuilder#86]
**Describe the bug**
The button spells 'Empy this slot'

**To Reproduce**
1. Open a world
2. Go to player inventory
3. Look at the bright red button right to 'Sort items:'

**Expected behavior**
The button spells 'Empty this slot'

**Screenshots**
![image](https://user-images.githubusercontent.com/37037712/213908033-102bb57e-5b4f-40e9-ba69-7662a240b4e0.png)

**Desktop (please complete the following information):**
 - OS: Any
 - Version: branch main, upcoming 0.5

**Additional context**
This misspelling is minor and does not affect gameplay

**Comment by piyush280599** [comment]
@Monniasza Can you please assign me this issue? I'm new to open source and would like to contribute in this. Any reply would be appreciated!

**Comment by Monniasza** [comment]
@piyush280599  I've assigned you.

**Comment by piyush280599** [comment]
@Monniasza Thank you for assigning me this issue. Since I'm a beginner so can you please guide me a little about file directory where the bug can be found?

**Comment by Monniasza** [comment]
@piyush280599 The misspelling is in a main resource bundle, at src/mmb/bundle.properties.
You can use Eclipse to test the project out before committing

**Comment by Monniasza** [comment]
The button looks good. Do you want to contribute further?

**Comment by piyush280599** [comment]
@Monniasza Sure! If you can assign me some other beginner friendly issues, I will be extremely grateful .
